[package]
name = "win-opacity"
version = "0.1.0"
authors = ["mcluck <mcluck90@gmail.com>"]

[dependencies]
winapi = "^0.3"

[target.'cfg(window)'.dependencies]
winapi = { version = "0.3", features = ["winuser"] }